# Server configuration
server.port=${SERVER_PORT:8080}

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger/OpenAPI configuration
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/v3/api-docs

# Custom properties
app.import.path=D:/STUDY/Cac_mon_tren_truong/TTCS/FE/Project-TTCS-BE/laptop_data/final_gallery_data.json
app.import.enabled=true
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION_MS}
app.upload.dir=D:/STUDY/Cac_mon_tren_truong/TTCS/FE/Project-TTCS-BE/backend/uploads

# CORS configuration
app.cors.allowed-origins=${FRONTEND_URL:http://localhost:3000}

# Mail Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# Frontend Redirect URI
app.oauth2.redirect-uri=${FRONTEND_URL:http://localhost:3000}/oauth2/redirect

# Logging
logging.level.org.springframework.security=DEBUG