spring.application.name=backend

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# HIBERNATE: Tự động đẻ bảng vào Database mới (Giữ nguyên)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port (Giữ nguyên)
server.port=8080

# Security (Giữ nguyên)
#spring.security.user.name=admin
#spring.security.user.password=123456

# Swagger / Open API Configuration
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.operations-sorter=alpha

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

# Google OAuth Configuration
google.oauth.client-id=${GOOGLE_OAUTH_CLIENT_ID:}

# Admin Configuration
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.admin.full-name=${ADMIN_FULLNAME}

# Pagination Configuration
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

# Frontend URL
front-end.url=${FRONTEND_URL}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true

